import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowDown, Box, Clock, LogOut, Search, User } from "lucide-react";
import BackButton from "@/components/BackButton";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import SignOutConfirm from "@/components/SignOutConfirm";
import { type LanguageKey, t } from "@/lib/i18n";
import { showSuccess } from "@/utils/toast";
import PageDocumentation, { type DocContent } from "@/components/PageDocumentation";

const IncomingMenu = () => {
  const navigate = useNavigate();

  const [lang] = useState<LanguageKey>(() => {
    const saved = localStorage.getItem("app.lang") as LanguageKey | null;
    return saved || "en";
  });
  const trans = useMemo(() => t(lang), [lang]);

  const [fullName, setFullName] = useState<string>("");
  useEffect(() => {
    const name = localStorage.getItem("gsi.full_name");
    if (name) setFullName(name);
  }, []);

  const [signOutOpen, setSignOutOpen] = useState(false);
  const onConfirmSignOut = () => {
    try {
      localStorage.removeItem("ln.token");
      localStorage.removeItem("gsi.id");
      localStorage.removeItem("gsi.full_name");
    } catch {}
    showSuccess(trans.signedOut);
    setSignOutOpen(false);
    navigate("/");
  };

  const tiles = [
    {
      key: "goodsReceipt",
      label: trans.incomingGoodsReceipt,
      icon: <ArrowDown className="h-10 w-10 text-red-700" />,
    },
    {
      key: "warehouseInspection",
      label: "Inspection",
      icon: <Search className="h-10 w-10 text-red-700" />,
    },
    {
      key: "putawaySuggestions",
      label: "Putaway",
      icon: <Box className="h-10 w-10 text-red-700" />,
    },
    {
      key: "deliveryNotice",
      label: trans.incomingDeliveryNotice,
      icon: <Clock className="h-10 w-10 text-red-700" />,
    },
  ] as const;

  const docs = useMemo(() => {
    const m = {
      en: {
        userTitle: "User Manual - Incoming Menu",
        techTitle: "Technical Documentation - Incoming Menu",
        userSections: [
          { title: "Purpose", body: "Choose an Incoming process: Goods Receipt, Inspection, Putaway, or Delivery Notice." },
          { title: "Tiles", bullets: ["Tap Goods Receipt to register received items.", "Other tiles are placeholders if not enabled."] },
        ],
        techSections: [
          { title: "Navigation", bullets: ["Routes to /menu/incoming/goods-receipt for goods receipt.", "Other routes can be enabled later."] },
          { title: "State", bullets: ["Reads user name for header; sign-out clears session."] },
        ],
        footer: "Generated by the application. Internal use.",
      },
      de: {
        userTitle: "Benutzerhandbuch - Eingang",
        techTitle: "Technische Dokumentation - Eingang",
        userSections: [
          { title: "Zweck", body: "Wählen Sie einen Eingangsvorgang: Wareneingang, Prüfung, Einlagerung, Lieferavis." },
          { title: "Kacheln", bullets: ["Wareneingang öffnet die Erfassung.", "Weitere Kacheln sind ggf. noch nicht aktiviert."] },
        ],
        techSections: [
          { title: "Navigation", bullets: ["Routen zu /menu/incoming/goods-receipt.", "Weitere Routen später aktivierbar."] },
          { title: "Status", bullets: ["Liest Benutzername; Abmelden löscht Sitzung."] },
        ],
        footer: "Von der Anwendung generiert. Interner Gebrauch.",
      },
      "es-MX": {
        userTitle: "Manual de Usuario - Entrada",
        techTitle: "Documentación Técnica - Entrada",
        userSections: [
          { title: "Propósito", body: "Elija un proceso de Entrada: Recepción, Inspección, Ubicación o Aviso de entrega." },
          { title: "Botones", bullets: ["Recepción abre el registro de mercancías.", "Otros botones pueden no estar activos."] },
        ],
        techSections: [
          { title: "Navegación", bullets: ["Ruta a /menu/incoming/goods-receipt.", "Rutas adicionales opcionales."] },
          { title: "Estado", bullets: ["Lee nombre de usuario; cerrar sesión limpia datos."] },
        ],
        footer: "Generado por la aplicación. Uso interno.",
      },
      "pt-BR": {
        userTitle: "Manual do Usuário - Entrada",
        techTitle: "Documentação Técnica - Entrada",
        userSections: [
          { title: "Objetivo", body: "Escolha um processo de Entrada: Recebimento, Inspeção, Endereçamento ou Aviso de entrega." },
          { title: "Blocos", bullets: ["Recebimento abre o registro.", "Outros blocos podem estar inativos."] },
        ],
        techSections: [
          { title: "Navegação", bullets: ["Rota para /menu/incoming/goods-receipt.", "Rotas adicionais opcionais."] },
          { title: "Estado", bullets: ["Lê nome; sair limpa sessão."] },
        ],
        footer: "Gerado pela aplicação. Uso interno.",
      },
    } as const;
    const mlang = m[lang];
    const userManual: DocContent = { title: mlang.userTitle, sections: mlang.userSections, footerNote: mlang.footer, filename: `User_Manual_IncomingMenu_${lang}` };
    const technicalDoc: DocContent = { title: mlang.techTitle, sections: mlang.techSections, footerNote: mlang.footer, filename: `Technical_Doc_IncomingMenu_${lang}` };
    return { userManual, technicalDoc };
  }, [lang]);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Top bar */}
      <div className="sticky top-0 z-10 bg-black text-white">
        <div className="mx-auto max-w-md px-4 py-3 flex items-center justify-between">
          <BackButton ariaLabel={trans.back} onClick={() => navigate("/menu")} />

          <div className="flex flex-col items-center flex-1">
            <div className="font-bold text-lg tracking-wide text-center">{trans.appIncoming.toUpperCase()}</div>
            <div className="mt-2 flex items-center gap-2 text-sm text-gray-200">
              <User className="h-4 w-4" />
              <span className="line-clamp-1">{fullName || ""}</span>
            </div>
          </div>

          <Button
            variant="ghost"
            size="icon"
            className="text-red-500 hover:text-red-600 hover:bg-white/10"
            aria-label={trans.signOut}
            onClick={() => setSignOutOpen(true)}
          >
            <LogOut className="h-6 w-6" />
          </Button>
        </div>
      </div>

      {/* Grid */}
      <div className="mx-auto max-w-md px-4 py-6 grid grid-cols-2 gap-4">
        {tiles.map((tile) => (
          <Card
            key={tile.key}
            className="rounded-md border-2 border-gray-200 bg-white p-6 flex flex-col items-center gap-3 shadow-sm cursor-pointer active:scale-[0.99] min-h-[160px]"
            onClick={() => {
              if (tile.key === "goodsReceipt") {
                navigate("/menu/incoming/goods-receipt");
              }
            }}
          >
            <div className="h-14 w-14 rounded-md border-2 border-red-700 flex items-center justify-center">
              {tile.icon}
            </div>
            <div className="text-sm font-medium text-gray-700 text-center">{tile.label}</div>
          </Card>
        ))}
      </div>

      {/* Docs download */}
      <div className="mx-auto max-w-md px-4 pb-6 flex justify-end">
        <PageDocumentation userManual={docs.userManual} technicalDoc={docs.technicalDoc} />
      </div>

      <SignOutConfirm
        open={signOutOpen}
        onOpenChange={setSignOutOpen}
        title={trans.signOutTitle}
        question={trans.signOutQuestion}
        yesLabel={trans.yes}
        noLabel={trans.no}
        onConfirm={onConfirmSignOut}
      />
    </div>
  );
};

export default IncomingMenu;