import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { LogOut, User, ArrowDownCircle, ArrowUpCircle, Warehouse, Package, Box, Settings } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import SignOutConfirm from "@/components/SignOutConfirm";
import { type LanguageKey, t } from "@/lib/i18n";
import { showSuccess } from "@/utils/toast";
import PageDocumentation, { type DocContent } from "@/components/PageDocumentation";

type AppTile = {
  key: string;
  label: string;
  icon: React.ReactNode;
};

function Menu() {
  const navigate = useNavigate();
  const [lang, setLang] = useState<LanguageKey>(() => {
    const saved = localStorage.getItem("app.lang") as LanguageKey | null;
    return saved || "en";
  });
  const trans = useMemo(() => t(lang), [lang]);

  const [fullName, setFullName] = useState<string>("");
  useEffect(() => {
    const name = localStorage.getItem("gsi.full_name");
    if (name) setFullName(name);
  }, []);

  const [signOutOpen, setSignOutOpen] = useState(false);

  const apps: AppTile[] = [
    { key: "incoming", label: trans.appIncoming, icon: <ArrowDownCircle className="h-10 w-10 text-red-700" /> },
    { key: "outgoing", label: trans.appOutgoing, icon: <ArrowUpCircle className="h-10 w-10 text-red-700" /> },
    { key: "infoStock", label: trans.appInfoStock, icon: <Warehouse className="h-10 w-10 text-red-700" /> },
    { key: "containers", label: trans.appContainers, icon: <Box className="h-10 w-10 text-red-700" /> },
    { key: "transport", label: trans.appTransport, icon: <Package className="h-10 w-10 text-red-700" /> },
    { key: "settings", label: trans.appSettings, icon: <Settings className="h-10 w-10 text-red-700" /> },
  ];

  const onConfirmSignOut = () => {
    // Clear local session data
    try {
      localStorage.removeItem("ln.token");
      localStorage.removeItem("gsi.id");
      localStorage.removeItem("gsi.full_name");
    } catch {}
    showSuccess(trans.signedOut);
    setSignOutOpen(false);
    navigate("/");
  };

  const docs = useMemo(() => {
    const m = {
      en: {
        userTitle: "User Manual - Main Menu",
        techTitle: "Technical Documentation - Main Menu",
        userSections: [
          { title: "Purpose", body: "Access all application modules (Incoming, Outgoing, Info/Stock, Containers, Transport, Settings)." },
          { title: "Header", bullets: ["Shows your name and a Sign out button."] },
          { title: "Tiles", bullets: ["Tap a tile to open its module.", "Transport tile opens the Transport module and prepares vehicle selection."] },
          { title: "Sign out", bullets: ["Clears local session data and returns to the login screen."] },
        ],
        techSections: [
          { title: "Navigation", bullets: ["Routes to /menu/incoming, /menu/info-stock, /menu/transport.", "For Transport, sets session flags to control vehicle dialog."] },
          { title: "State & Storage", bullets: ["Reads gsi.full_name from localStorage for header.", "On sign-out clears ln.token, gsi.* keys."] },
          { title: "UI", bullets: ["Tiles use shadcn/ui Card; header uses Button and Lucide icons."] },
        ],
        footer: "Generated by the application. Internal use.",
      },
      de: {
        userTitle: "Benutzerhandbuch - Hauptmenü",
        techTitle: "Technische Dokumentation - Hauptmenü",
        userSections: [
          { title: "Zweck", body: "Zugriff auf alle Module (Eingang, Ausgang, Info/Bestand, Behälter, Transport, Einstellungen)." },
          { title: "Kopfbereich", bullets: ["Zeigt Ihren Namen und eine Abmelden-Schaltfläche."] },
          { title: "Kacheln", bullets: ["Tippen Sie auf eine Kachel, um das Modul zu öffnen.", "Transport öffnet das Modul und bereitet die Fahrzeugauswahl vor."] },
          { title: "Abmelden", bullets: ["Löscht lokale Sitzungsdaten und kehrt zum Login zurück."] },
        ],
        techSections: [
          { title: "Navigation", bullets: ["Routen zu /menu/incoming, /menu/info-stock, /menu/transport.", "Für Transport werden Sitzungs-Flags gesetzt (Dialog)."] },
          { title: "Status & Speicherung", bullets: ["Liest gsi.full_name aus localStorage.", "Beim Abmelden werden ln.token, gsi.* gelöscht."] },
          { title: "UI", bullets: ["Kacheln mit shadcn/ui Card; Kopf mit Button und Lucide-Icons."] },
        ],
        footer: "Von der Anwendung generiert. Interner Gebrauch.",
      },
      "es-MX": {
        userTitle: "Manual de Usuario - Menú principal",
        techTitle: "Documentación Técnica - Menú principal",
        userSections: [
          { title: "Propósito", body: "Acceso a módulos (Entrada, Salida, Info/Inventario, Contenedores, Transporte, Configuración)." },
          { title: "Encabezado", bullets: ["Muestra su nombre y botón de Cerrar sesión."] },
          { title: "Azulejos", bullets: ["Toque un módulo para abrirlo.", "Transporte abre el módulo y prepara la selección de vehículo."] },
          { title: "Cerrar sesión", bullets: ["Limpia la sesión local y vuelve al login."] },
        ],
        techSections: [
          { title: "Navegación", bullets: ["Rutas a /menu/incoming, /menu/info-stock, /menu/transport.", "Para Transporte se establecen banderas de sesión."] },
          { title: "Estado y almacenamiento", bullets: ["Lee gsi.full_name del localStorage.", "En salida borra ln.token y claves gsi.*."] },
          { title: "UI", bullets: ["Tarjetas (Card) de shadcn/ui; encabezado con Button e íconos Lucide."] },
        ],
        footer: "Generado por la aplicación. Uso interno.",
      },
      "pt-BR": {
        userTitle: "Manual do Usuário - Menu principal",
        techTitle: "Documentação Técnica - Menu principal",
        userSections: [
          { title: "Objetivo", body: "Acessar módulos (Entrada, Saída, Info/Estoque, Contêineres, Transporte, Configurações)." },
          { title: "Cabeçalho", bullets: ["Exibe seu nome e botão Sair."] },
          { title: "Blocos", bullets: ["Toque em um módulo para abrir.", "Transporte abre o módulo e prepara a seleção de veículo."] },
          { title: "Sair", bullets: ["Limpa dados locais e retorna ao login."] },
        ],
        techSections: [
          { title: "Navegação", bullets: ["Rotas para /menu/incoming, /menu/info-stock, /menu/transport.", "Define flags de sessão para Transporte."] },
          { title: "Estado e armazenamento", bullets: ["Lê gsi.full_name do localStorage.", "Em sair remove ln.token e gsi.*."] },
          { title: "UI", bullets: ["Cards do shadcn/ui; cabeçalho com Button e Lucide."] },
        ],
        footer: "Gerado pela aplicação. Uso interno.",
      },
    } as const;
    const mlang = m[lang];
    const userManual: DocContent = { title: mlang.userTitle, sections: mlang.userSections, footerNote: mlang.footer, filename: `User_Manual_Menu_${lang}` };
    const technicalDoc: DocContent = { title: mlang.techTitle, sections: mlang.techSections, footerNote: mlang.footer, filename: `Technical_Doc_Menu_${lang}` };
    return { userManual, technicalDoc };
  }, [lang]);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Top bar */}
      <div className="sticky top-0 z-10 bg-black text-white">
        <div className="mx-auto max-w-md px-4 py-3 flex items-center justify-between">
          <div className="flex flex-col">
            <div className="text-center w-full font-bold text-lg tracking-wide">{trans.menu}</div>
            <div className="mt-2 flex items-center gap-2 text-sm text-gray-200 justify-center">
              <User className="h-4 w-4" />
              <span className="line-clamp-1">{fullName || ""}</span>
            </div>
          </div>
          <Button
            variant="ghost"
            size="icon"
            className="text-red-500 hover:text-red-600 hover:bg-white/10"
            aria-label={trans.signOut}
            onClick={() => setSignOutOpen(true)}
          >
            <LogOut className="h-6 w-6" />
          </Button>
        </div>
      </div>

      {/* Grid of app tiles */}
      <div className="mx-auto max-w-md px-4 py-6 grid grid-cols-2 gap-4">
        {apps.map((app) => (
          <Card
            key={app.key}
            className="rounded-md border-2 border-gray-200 bg-white p-6 flex flex-col items-center justify-center gap-3 shadow-sm cursor-pointer active:scale-[0.99] min-h-[160px]"
            onClick={() => {
              if (app.key === "incoming") {
                navigate("/menu/incoming");
              }
              if (app.key === "infoStock") {
                navigate("/menu/info-stock");
              }
              if (app.key === "transport") {
                // Mark that we're entering Transport from the main menu and force dialog to open
                sessionStorage.setItem("transport.fromMain", "1");
                // Clear previous in-transport selection so user confirms Vehicle-ID again
                sessionStorage.removeItem("transport.selected");
                navigate("/menu/transport");
              }
            }}
          >
            <div className="h-14 w-14 rounded-md border-2 border-red-700 flex items-center justify-center overflow-hidden">
              {app.icon}
            </div>
            <div className="text-sm font-medium text-gray-700 text-center">{app.label}</div>
          </Card>
        ))}
      </div>

      {/* Docs download */}
      <div className="mx-auto max-w-md px-4 pb-6 flex justify-end">
        <PageDocumentation userManual={docs.userManual} technicalDoc={docs.technicalDoc} />
      </div>

      {/* Sign-out confirmation dialog */}
      <SignOutConfirm
        open={signOutOpen}
        onOpenChange={setSignOutOpen}
        title={trans.signOutTitle}
        question={trans.signOutQuestion}
        yesLabel={trans.yes}
        noLabel={trans.no}
        onConfirm={onConfirmSignOut}
      />
    </div>
  );
}

export default Menu;