// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { getGsiSessionAuthorizationHeader } from '@/lib/gsi-session';

const SUPABASE_URL = "https://lkmdrhprvumenzzykmxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrbWRyaHBydnVtZW56enlrbXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4MjIxNzgsImV4cCI6MjA4MTM5ODE3OH0.h0sXx8Du1c4ynsrI6eldxtZp_hDqfIxyUYArxAQ3KwM";

const supabaseClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const originalInvoke = supabaseClient.functions.invoke.bind(supabaseClient.functions);

supabaseClient.functions.invoke = ((functionName, options) => {
  const authHeader = getGsiSessionAuthorizationHeader();
  const mergedHeaders = {
    ...((options?.headers as Record<string, string> | undefined) || {}),
    ...(authHeader ? { Authorization: authHeader } : {}),
  };

  return originalInvoke(functionName, {
    ...options,
    headers: mergedHeaders,
  });
}) as typeof supabaseClient.functions.invoke;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = supabaseClient;