// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zsbtweyyshnugrwrixst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzYnR3ZXl5c2hudWdyd3JpeHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMDEwMjQsImV4cCI6MjA4NzY3NzAyNH0.t49rXlLtxZBRBwu0O-NKZqBEF-PBE96ot4ci9hKHWKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
