// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lkmdrhprvumenzzykmxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrbWRyaHBydnVtZW56enlrbXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4MjIxNzgsImV4cCI6MjA4MTM5ODE3OH0.h0sXx8Du1c4ynsrI6eldxtZp_hDqfIxyUYArxAQ3KwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);